//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogExample.Data.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public int MenuId { get; set; }
        public int AdminId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string BlogContent { get; set; }
        public string Tag { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime AddDate { get; set; }
        public string PageSlug { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
        public virtual SiteMenu SiteMenu { get; set; }
    }
}
