//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogExample.Data.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int Id { get; set; }
        public int TopCategoryId { get; set; }
        public int MenuId { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual SiteMenu SiteMenu { get; set; }
    }
}
